// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClipboard creates a new instance of MockClipboard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClipboard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClipboard {
	mock := &MockClipboard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClipboard is an autogenerated mock type for the Clipboard type
type MockClipboard struct {
	mock.Mock
}

type MockClipboard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClipboard) EXPECT() *MockClipboard_Expecter {
	return &MockClipboard_Expecter{mock: &_m.Mock}
}

// WriteAll provides a mock function for the type MockClipboard
func (_mock *MockClipboard) WriteAll(text string) error {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for WriteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClipboard_WriteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAll'
type MockClipboard_WriteAll_Call struct {
	*mock.Call
}

// WriteAll is a helper method to define mock.On call
//   - text string
func (_e *MockClipboard_Expecter) WriteAll(text interface{}) *MockClipboard_WriteAll_Call {
	return &MockClipboard_WriteAll_Call{Call: _e.mock.On("WriteAll", text)}
}

func (_c *MockClipboard_WriteAll_Call) Run(run func(text string)) *MockClipboard_WriteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClipboard_WriteAll_Call) Return(err error) *MockClipboard_WriteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClipboard_WriteAll_Call) RunAndReturn(run func(text string) error) *MockClipboard_WriteAll_Call {
	_c.Call.Return(run)
	return _c
}
