.nh
.TH "OGLE" "1" "Jun 2026" "" ""

.SH NAME
ogle - A TUI for monitoring Docker Compose projects.


.SH SYNOPSIS
\fBogle [flags]\fP


.SH DESCRIPTION
A TUI for monitoring Docker Compose projects.


.SH OPTIONS
\fB--config\fP=""
	config file (default is $HOME/.ogle/config)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ogle

.PP
\fB--log-buffer-cap\fP=0
	maximum log lines buffered per service (env: OGLE_LOG_BUFFER_CAP; default 1000)

.PP
\fB--pprof-addr\fP=""
	pprof HTTP server address (e.g. localhost:6060)

.PP
\fB-f\fP, \fB--project-file\fP=""
	path to docker compose file

.PP
\fB--theme\fP=""
	theme name; built-ins: "default", "default_light", "catppuccino_frappe", "catppuccino_latte", "catppuccino_macchiato", "catppuccino_mocha", "solarized_dark", "solarized_light" (env: OGLE_THEME)


.SH SEE ALSO
\fBogle-version(1)\fP
