// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"charm.land/bubbletea/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDocker creates a new instance of MockDocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocker {
	mock := &MockDocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDocker is an autogenerated mock type for the Docker type
type MockDocker struct {
	mock.Mock
}

type MockDocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocker) EXPECT() *MockDocker_Expecter {
	return &MockDocker_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockDocker
func (_mock *MockDocker) Connect(ctx context.Context) tea.Cmd {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context) tea.Cmd); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDocker_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDocker_Expecter) Connect(ctx interface{}) *MockDocker_Connect_Call {
	return &MockDocker_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *MockDocker_Connect_Call) Run(run func(ctx context.Context)) *MockDocker_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDocker_Connect_Call) Return(cmd tea.Cmd) *MockDocker_Connect_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Connect_Call) RunAndReturn(run func(ctx context.Context) tea.Cmd) *MockDocker_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function for the type MockDocker
func (_mock *MockDocker) Inspect(ctx context.Context, containerID string) tea.Cmd {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) tea.Cmd); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockDocker_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockDocker_Expecter) Inspect(ctx interface{}, containerID interface{}) *MockDocker_Inspect_Call {
	return &MockDocker_Inspect_Call{Call: _e.mock.On("Inspect", ctx, containerID)}
}

func (_c *MockDocker_Inspect_Call) Run(run func(ctx context.Context, containerID string)) *MockDocker_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDocker_Inspect_Call) Return(cmd tea.Cmd) *MockDocker_Inspect_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Inspect_Call) RunAndReturn(run func(ctx context.Context, containerID string) tea.Cmd) *MockDocker_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// Ps provides a mock function for the type MockDocker
func (_mock *MockDocker) Ps(ctx context.Context, composeFile string, projectName string) tea.Cmd {
	ret := _mock.Called(ctx, composeFile, projectName)

	if len(ret) == 0 {
		panic("no return value specified for Ps")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) tea.Cmd); ok {
		r0 = returnFunc(ctx, composeFile, projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Ps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ps'
type MockDocker_Ps_Call struct {
	*mock.Call
}

// Ps is a helper method to define mock.On call
//   - ctx context.Context
//   - composeFile string
//   - projectName string
func (_e *MockDocker_Expecter) Ps(ctx interface{}, composeFile interface{}, projectName interface{}) *MockDocker_Ps_Call {
	return &MockDocker_Ps_Call{Call: _e.mock.On("Ps", ctx, composeFile, projectName)}
}

func (_c *MockDocker_Ps_Call) Run(run func(ctx context.Context, composeFile string, projectName string)) *MockDocker_Ps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDocker_Ps_Call) Return(cmd tea.Cmd) *MockDocker_Ps_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Ps_Call) RunAndReturn(run func(ctx context.Context, composeFile string, projectName string) tea.Cmd) *MockDocker_Ps_Call {
	_c.Call.Return(run)
	return _c
}

// Rebuild provides a mock function for the type MockDocker
func (_mock *MockDocker) Rebuild(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd {
	ret := _mock.Called(ctx, composeFile, projectName, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for Rebuild")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) tea.Cmd); ok {
		r0 = returnFunc(ctx, composeFile, projectName, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Rebuild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rebuild'
type MockDocker_Rebuild_Call struct {
	*mock.Call
}

// Rebuild is a helper method to define mock.On call
//   - ctx context.Context
//   - composeFile string
//   - projectName string
//   - serviceName string
func (_e *MockDocker_Expecter) Rebuild(ctx interface{}, composeFile interface{}, projectName interface{}, serviceName interface{}) *MockDocker_Rebuild_Call {
	return &MockDocker_Rebuild_Call{Call: _e.mock.On("Rebuild", ctx, composeFile, projectName, serviceName)}
}

func (_c *MockDocker_Rebuild_Call) Run(run func(ctx context.Context, composeFile string, projectName string, serviceName string)) *MockDocker_Rebuild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDocker_Rebuild_Call) Return(cmd tea.Cmd) *MockDocker_Rebuild_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Rebuild_Call) RunAndReturn(run func(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd) *MockDocker_Rebuild_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type MockDocker
func (_mock *MockDocker) Restart(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd {
	ret := _mock.Called(ctx, composeFile, projectName, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) tea.Cmd); ok {
		r0 = returnFunc(ctx, composeFile, projectName, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockDocker_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - composeFile string
//   - projectName string
//   - serviceName string
func (_e *MockDocker_Expecter) Restart(ctx interface{}, composeFile interface{}, projectName interface{}, serviceName interface{}) *MockDocker_Restart_Call {
	return &MockDocker_Restart_Call{Call: _e.mock.On("Restart", ctx, composeFile, projectName, serviceName)}
}

func (_c *MockDocker_Restart_Call) Run(run func(ctx context.Context, composeFile string, projectName string, serviceName string)) *MockDocker_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDocker_Restart_Call) Return(cmd tea.Cmd) *MockDocker_Restart_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Restart_Call) RunAndReturn(run func(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd) *MockDocker_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockDocker
func (_mock *MockDocker) Start(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd {
	ret := _mock.Called(ctx, composeFile, projectName, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) tea.Cmd); ok {
		r0 = returnFunc(ctx, composeFile, projectName, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDocker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - composeFile string
//   - projectName string
//   - serviceName string
func (_e *MockDocker_Expecter) Start(ctx interface{}, composeFile interface{}, projectName interface{}, serviceName interface{}) *MockDocker_Start_Call {
	return &MockDocker_Start_Call{Call: _e.mock.On("Start", ctx, composeFile, projectName, serviceName)}
}

func (_c *MockDocker_Start_Call) Run(run func(ctx context.Context, composeFile string, projectName string, serviceName string)) *MockDocker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDocker_Start_Call) Return(cmd tea.Cmd) *MockDocker_Start_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Start_Call) RunAndReturn(run func(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd) *MockDocker_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockDocker
func (_mock *MockDocker) Stop(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd {
	ret := _mock.Called(ctx, composeFile, projectName, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) tea.Cmd); ok {
		r0 = returnFunc(ctx, composeFile, projectName, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockDocker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockDocker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
//   - composeFile string
//   - projectName string
//   - serviceName string
func (_e *MockDocker_Expecter) Stop(ctx interface{}, composeFile interface{}, projectName interface{}, serviceName interface{}) *MockDocker_Stop_Call {
	return &MockDocker_Stop_Call{Call: _e.mock.On("Stop", ctx, composeFile, projectName, serviceName)}
}

func (_c *MockDocker_Stop_Call) Run(run func(ctx context.Context, composeFile string, projectName string, serviceName string)) *MockDocker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDocker_Stop_Call) Return(cmd tea.Cmd) *MockDocker_Stop_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockDocker_Stop_Call) RunAndReturn(run func(ctx context.Context, composeFile string, projectName string, serviceName string) tea.Cmd) *MockDocker_Stop_Call {
	_c.Call.Return(run)
	return _c
}
