// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"charm.land/bubbletea/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatcher creates a new instance of MockWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatcher {
	mock := &MockWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatcher is an autogenerated mock type for the Watcher type
type MockWatcher struct {
	mock.Mock
}

type MockWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatcher) EXPECT() *MockWatcher_Expecter {
	return &MockWatcher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockWatcher
func (_mock *MockWatcher) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatcher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWatcher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWatcher_Expecter) Close() *MockWatcher_Close_Call {
	return &MockWatcher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWatcher_Close_Call) Run(run func()) *MockWatcher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcher_Close_Call) Return(err error) *MockWatcher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatcher_Close_Call) RunAndReturn(run func() error) *MockWatcher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Dir provides a mock function for the type MockWatcher
func (_mock *MockWatcher) Dir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWatcher_Dir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dir'
type MockWatcher_Dir_Call struct {
	*mock.Call
}

// Dir is a helper method to define mock.On call
func (_e *MockWatcher_Expecter) Dir() *MockWatcher_Dir_Call {
	return &MockWatcher_Dir_Call{Call: _e.mock.On("Dir")}
}

func (_c *MockWatcher_Dir_Call) Run(run func()) *MockWatcher_Dir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcher_Dir_Call) Return(s string) *MockWatcher_Dir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWatcher_Dir_Call) RunAndReturn(run func() string) *MockWatcher_Dir_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockWatcher
func (_mock *MockWatcher) Next() tea.Cmd {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func() tea.Cmd); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockWatcher_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockWatcher_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockWatcher_Expecter) Next() *MockWatcher_Next_Call {
	return &MockWatcher_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockWatcher_Next_Call) Run(run func()) *MockWatcher_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcher_Next_Call) Return(cmd tea.Cmd) *MockWatcher_Next_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockWatcher_Next_Call) RunAndReturn(run func() tea.Cmd) *MockWatcher_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type MockWatcher
func (_mock *MockWatcher) Snapshot() tea.Cmd {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 tea.Cmd
	if returnFunc, ok := ret.Get(0).(func() tea.Cmd); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}
	return r0
}

// MockWatcher_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockWatcher_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockWatcher_Expecter) Snapshot() *MockWatcher_Snapshot_Call {
	return &MockWatcher_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockWatcher_Snapshot_Call) Run(run func()) *MockWatcher_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcher_Snapshot_Call) Return(cmd tea.Cmd) *MockWatcher_Snapshot_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockWatcher_Snapshot_Call) RunAndReturn(run func() tea.Cmd) *MockWatcher_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockWatcher
func (_mock *MockWatcher) Start(sendMsg func(tea.Msg)) {
	_mock.Called(sendMsg)
	return
}

// MockWatcher_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWatcher_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - sendMsg func(tea.Msg)
func (_e *MockWatcher_Expecter) Start(sendMsg interface{}) *MockWatcher_Start_Call {
	return &MockWatcher_Start_Call{Call: _e.mock.On("Start", sendMsg)}
}

func (_c *MockWatcher_Start_Call) Run(run func(sendMsg func(tea.Msg))) *MockWatcher_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(tea.Msg)
		if args[0] != nil {
			arg0 = args[0].(func(tea.Msg))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWatcher_Start_Call) Return() *MockWatcher_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWatcher_Start_Call) RunAndReturn(run func(sendMsg func(tea.Msg))) *MockWatcher_Start_Call {
	_c.Run(run)
	return _c
}
